### ISSUE TITLE
Calendar being shown despite unfocus

### ISSUE THREAD

**Issue by entioentio** [Vuepic/vue3-date-time-picker#33] opened 2021-11-01 10:29 UTC
**Describe the bug**
When the text input is focused and tab key is pressed, the next component is focused. However the calendar is still being shown, it doesn't hide.

**Comment by Jasenkoo** [comment] 2021-11-04 17:32
The issue is fixed in the new version [2.3.3](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.3.3)

**Closed by Jasenkoo** 2021-11-04 17:32 UTC
Labels: bug
