### ISSUE TITLE
Programmatically set the value of a time-picker not working

### ISSUE THREAD

**Issue by ekkode** [Vuepic/vue3-date-time-picker#37] opened 2021-11-03 06:11 UTC
**Describe the bug**
I try to set the value programmatically to a time-picker, however the value is not visible until I click on the input.

**To Reproduce**
Please see the example here https://codesandbox.io/s/vue3-date-time-picker-demo-forked-7zney?file=/src/components/Demo.vue

**Expected behavior**
I expect that the value in the field to be updated without necessary clicking on the input.

**Comment by ekkode** [comment] 2021-11-03 08:56
This is working only if I do a rerender of the component, but is not quite nice. 

Please check here: 
https://codesandbox.io/s/vue3-date-time-picker-demo-forked-0rfv1?file=/src/components/Demo.vue

Or do I miss something?

**Comment by Jasenkoo** [comment] 2021-11-03 09:08
The issue was fixed (#20). Please update the component to at least 2.1.8.

On the latest, working fine: https://codesandbox.io/s/vue3-date-time-picker-demo-forked-9h5cd

**Comment by ekkode** [comment] 2021-11-03 09:33
@Jasenkoo I just did it however still not working plase check here : https://codesandbox.io/s/vue3-date-time-picker-demo-forked-7zney?file=/src/components/Demo.vue

**Comment by Jasenkoo** [comment] 2021-11-03 10:30
@ekkode Sorry, my bad, I checked on working sandbox. I will fix it in the next patch.

**Comment by ekkode** [comment] 2021-11-03 10:52
Thanks!

In the meantime I will use the rerender workaround as I said here: https://github.com/Vuepic/vue3-date-time-picker/issues/37#issuecomment-958755398

**Comment by Jasenkoo** [comment] 2021-11-04 17:32
The issue is fixed in the new version [2.3.3](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.3.3)

**Closed by Jasenkoo** 2021-11-04 17:32 UTC
Labels: bug, good first issue

**Comment by videk11** [comment] 2021-11-09 09:19
Hello @Jasenkoo 

I think this issue is still present. If you use only timepicker and you have a custom #dp-input slot and then set model value, you have to click into the custom input. Only after that, the value is updated in the input.

**Comment by Jasenkoo** [comment] 2021-11-09 09:23
@videk11 Will check
