### ISSUE TITLE
Time picker doesn't auto-apply value

### ISSUE THREAD

**Issue by misha** [Vuepic/vue3-date-time-picker#10] opened 2021-09-29 05:02 UTC
**Describe the bug**

`enableTimePicker` and `autoApply` don't work together correctly.

The time doesn't apply unless you select a date from the calendar again.

**To Reproduce**

```vue
<datepicker
  :enable-time-picker="true"
  :auto-apply="true"
/>
```

Set up a date picker with the properties above.

**Expected behavior**

After switching to the time input, adjusting the hours or minutes should update the date shown right away.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 94.0.4606.61 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

N/A

**Comment by Jasenkoo** [comment] 2021-09-29 12:40
Will be fixed in the next version. Tnx for reporting

**Comment by Jasenkoo** [comment] 2021-09-29 19:50
The issue is fixed.

New version [2.1.3](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.1.3) is now live.

Quick tip, `enable-time-picker` prop is enabled by default

**Closed by Jasenkoo** 2021-09-29 19:50 UTC
Labels: bug, good first issue
