### ISSUE TITLE
altPosition not work correctly

### ISSUE THREAD

**Issue by nipanimaju** [Vuepic/vue3-date-time-picker#97] opened 2022-02-09 08:51 UTC
If is enought space in the top Datepicker recalculate top position, when is enought space in the bottom Datepicker take my custom 'top' position.

code: 
```
            <Datepicker v-else-if="getInputType(name) == 'date'"
              v-model="gObject[name]"
              autoPosition="false"
              :altPosition="() => { return { top: '80px', left: '50%', transform: 'translateX(-50%)' } }"
              :enableTimePicker="false"
              :placeholder="dateConvert(name, value)"
              @closed="dateWithoutTime(gObject[name], name)"
              :locale="$i18n.locale"
              hideInputIcon/>
```
Windows 10 64, Chrome
![111a](https://user-images.githubusercontent.com/50579605/153159373-cde435ea-7b27-4fa4-aaf0-69dd3a64af13.jpg)
![111b](https://user-images.githubusercontent.com/50579605/153159383-e2f67c17-280f-4114-b0a7-d66018da95dd.jpg)

**Comment by Jasenkoo** [comment] 2022-02-09 16:54
I just got the time to take a deeper look, I am not sure what is happening, can you explain a little bit better?

**Comment by nipanimaju** [comment] 2022-02-10 15:13
```
            <Datepicker v-else-if="getInputType(name) == 'date'"
              v-model="gObject[name]"
              :enableTimePicker="false"
              autoPosition="false"
              :altPosition="() => { return { top: '80px', left: '50%', transform: 'translateX(-50%)' } }"
              :placeholder="dateConvert(name, value)"
              @closed="dateWithoutTime(gObject[name], name)"
              :locale="$i18n.locale"
              teleport=".table-nav"
              hideInputIcon/>
```
Datepicker is created dynamicly in table with another input fields (text, number). All this fields are in wrapper .table-nav where ist set teleport, this ist scrollable div with height auto. On Large screen everything is fine i dont need altPosition, but on mobile i need to show Datapicker in the midle on screen and there i added altPosition. When Datepicker field is at the top of the application in css property is my custom top: 80px, but when Datepicker field is at the bottom my custom pos is ignored (or recalculate?) is 350px sometimes 500px. Screen one - everyting ok, sceen two - not. Red square shows the current position of the Datapicker field
![screen](https://user-images.githubusercontent.com/50579605/153437001-52191ba2-81bd-4312-bbc3-3b5cb9e9fde7.jpg)
![screen2](https://user-images.githubusercontent.com/50579605/153437007-5d593678-8bdd-4479-aa07-1f8f0f888a3b.jpg)

**Comment by Jasenkoo** [comment] 2022-02-10 16:40
Tnx, I know what is causing it, will be fixed

**Closed** 2022-02-13 15:53 UTC
Labels: bug

**Comment by nipanimaju** [comment] 2022-02-16 09:36
I have updated the package but the problem persists

**Comment by ekkode** [comment] 2022-02-19 11:21
@Jasenkoo I confirm that the issue is still present in v2.6.0. 
I have downgraded to v2.3.6 and everything is ok, it seems that the problem started from v2.4.0

**Comment by Jasenkoo** [comment] 2022-02-19 14:05
@ekkode Did you set `autoPosition` to `false`?
