### ISSUE TITLE
The programmatically set date is displayed only after clicking on the input field

### ISSUE THREAD

**Issue by Gumlokt** [Vuepic/vue3-date-time-picker#73] opened 2021-12-24 09:52 UTC
**Describe the bug**
If the model value is stored in the Vuex and if a date picker is updated programmatically (without using the actual UI of the date picker itself) the input field is not refreshed immediately. Browser displays programmatically set date only after clicking into the datepicker field.

**To Reproduce**
I reproduced the error here: [https://codesandbox.io/s/elegant-margulis-tqbpj](https://codesandbox.io/s/elegant-margulis-tqbpj)
(There, the "Populate" button programmatically sets the dates in the Vuex model values).

**Expected behavior**
I would like that when the model value is programmatically updated, the input field is also automatically updated (without having to click on the input field)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: latest versions of Chrome and Firefox

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy S20+
 - OS: Android 11
 - Browser: latest version of Firefox

**Screenshot**
![vue3dtp](https://user-images.githubusercontent.com/9348101/147340901-be4ceb6a-d520-4b5b-bd3c-930804886b4e.jpg)

**Comment by Jasenkoo** [comment] 2021-12-24 11:25
Thx for providing the reproduction link, will be fixed

**Comment by Jasenkoo** [comment] 2021-12-24 16:54
Bust my head to find out what is causing it, since I couldn't reproduce with the same store setup, but on your example, it was not updating, cloned everything, and everything updated except the value in the input.

Then I found out what is happening. The issue was in the `<form>` tag and `<button>` inside the form. 

To have the input update properly use either one of the provided solutions

1. Add `.prevent` on `@click`, e.g. `@click.prevent="fillInNewPermit"`
2. Change `button` type to button e.g. `<button type="button">`

**Closed by Jasenkoo** 2021-12-24 16:54 UTC
Labels: bug

**Comment by Gumlokt** [comment] 2021-12-26 06:21
Thank you so much for your help! And thanks for the cool component! I've been racking my brain for 2 days and couldn't see my error, even though it was in plain sight...
